#!/usr/bin/env python3
"""Regenerate qa_output/INDEX.md: the table of contents for screenshot review.

Usage: python3 tests/tools/make_qa_index.py [qa_output_dir]

Reads every <topic>/<date_time>/manifest.json (written by PlaytestKit) and the
run_meta/<date_time>.json files (written by tests/run_tests.sh). Output tells a
reviewer, for the NEWEST run: which images exist, what each shows, what is
expected, and which ones CHANGED since the previous run (same renderer) and so
need a look. Unchanged images can be skipped. Safe to run any time; never
deletes anything.

The newest run is taken from run_meta (it exists even if a step crashed before
writing its manifest), and every topic that earlier runs had but this run lacks
is shown as MISSING, so a crashed step can never hide behind an older green run.
Exit code 1 if a manifest is unreadable (the runner counts that as a failure).
"""
import json
import pathlib
import sys

THRESHOLD = 0.002  # fraction of pixels (160x90 thumbnail, luminance diff > 0.06) that must differ to count as "changed"

base = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "qa_output")
problems = []
runs = {}  # stamp -> {topic: manifest dict}
for manifest in sorted(base.glob("*/*/manifest.json")):
    try:
        data = json.loads(manifest.read_text())
        if not isinstance(data["images"], list):
            raise TypeError("'images' is not a list")
        for img in data["images"]:
            if not isinstance(img, dict) or "file" not in img:
                raise TypeError("an image entry is not an object with a 'file'")
            if img.get("changed_vs_previous") is not None and not isinstance(img["changed_vs_previous"], (int, float)):
                raise TypeError("changed_vs_previous is not a number")
        runs.setdefault(data["run"], {})[data["topic"]] = data
    except (ValueError, KeyError, TypeError, AttributeError) as e:
        problems.append(f"unreadable manifest {manifest}: {type(e).__name__} {e}")


meta = {}
meta_dir = base / "run_meta"
for f in meta_dir.glob("*.json") if meta_dir.exists() else []:
    try:
        meta[f.stem] = json.loads(f.read_text())
        if not isinstance(meta[f.stem], dict):
            raise TypeError("run_meta is not an object")
    except (ValueError, TypeError) as e:
        meta.pop(f.stem, None)
        problems.append(f"unreadable run_meta {f}: {type(e).__name__} {e}")

all_topics = sorted({t for r in runs.values() for t in r})
lines = [
    "# QA screenshot index",
    "",
    "Generated by `tests/tools/make_qa_index.py` (the test runner calls it). Do not edit by hand.",
    "",
    "**Layout:** `qa_output/<topic>/<YYYY-MM-DD_HH-MM-SS>/<NN>_<name>.png` plus a `manifest.json` in each run",
    "folder. The folder name is ONLY the date and time of the run. Topics: camera, environment, nature,",
    "player, movement, village, character, animation, daynight. Nothing here is ever deleted. `run_meta/<date_time>.json` records the git branch,",
    "commit, renderer and result of each run.",
    "",
    "**How to review:** read the newest run below. Open every image marked **REVIEW** (new, or more than",
    f"{THRESHOLD:.1%} of its pixels changed since the previous run with the SAME renderer). Skip unchanged",
    "images unless a finding needs a baseline (\"unchanged\" means under that threshold, not byte-identical:",
    "use `md5sum` to test for identical files). `what` says what the image shows; `expect` says what a",
    "correct frame looks like. CI artifacts have no history, so every image there is new.",
    "",
]

stamps = sorted(set(runs) | set(meta), reverse=True)
if not stamps:
    lines.append("_No runs yet. Run `tests/run_tests.sh`._")
else:
    latest = stamps[0]
    m = meta.get(latest, {})
    lines += [f"## Latest run: {latest}", ""]
    if m:
        lines.append(f"Branch `{m.get('branch', '?')}`, commit `{m.get('commit', '?')}`"
                     f"{' (uncommitted changes)' if m.get('dirty') else ''}, renderer {m.get('renderer', '?')}, "
                     f"result **{m.get('result', '?')}**.")
        lines.append("")
        if str(m.get("result", "")).startswith("FAIL"):
            lines += [f"> **WARNING: this run FAILED ({m['result']}). Its screenshots may be incomplete or wrong: "
                      "fix the failure before reviewing images.**", ""]
    review = 0
    present = runs.get(latest, {})
    for topic in all_topics:
        if topic not in present:
            lines += [f"### {topic}", "",
                      f"> **MISSING: no `{topic}` manifest for run {latest}.** The step that makes these images "
                      "crashed, was skipped, or never ran. Do not review an older run as if it were this one.", ""]
            review += 1
            continue
        lines += [f"### {topic}", "", "| Review? | File | What it shows | Expected | Changed vs previous |", "|---|---|---|---|---|"]
        for img in present[topic]["images"]:
            changed = img.get("changed_vs_previous")
            if changed is None:
                flag, change = "**REVIEW** (new)", "new image (no earlier run with this renderer)"
            elif changed > THRESHOLD:
                flag, change = "**REVIEW**", f"{changed:.1%} of pixels (vs {img.get('previous_run')})"
            else:
                flag, change = "unchanged", f"{changed:.1%}"
            review += flag.startswith("**")
            what = img.get("what", "").replace("|", "/")
            expect = img.get("expect", "").replace("|", "/")
            lines.append(f"| {flag} | `{topic}/{latest}/{img['file']}` | {what} | {expect} | {change} |")
        lines.append("")
    lines += [f"**{review} item(s) to review in the latest run.**", "", "## All runs (newest first)", "",
              "| Run | Images | Branch | Commit | Renderer | Result |", "|---|---|---|---|---|---|"]
    for stamp in stamps:
        count = sum(len(v["images"]) for v in runs.get(stamp, {}).values())
        m = meta.get(stamp, {})
        lines.append(f"| {stamp} | {count} | {m.get('branch', '')} | {m.get('commit', '')} | {m.get('renderer', '')} | {m.get('result', '')} |")
    lines.append("")

if problems:
    lines += ["## Problems reading the data", ""] + [f"- {p}" for p in problems] + [""]

(base / "INDEX.md").write_text("\n".join(lines))
print(f"wrote {base / 'INDEX.md'}")
for p in problems:
    print("ERROR: " + p)
sys.exit(1 if problems else 0)
